
service: return-html # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x

functions:
  html:
    handler: handler.html
    events:
      - http:
          path: hello
          method: get
          integration: lambda
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')
